### ISSUE TITLE
Ecovacs Deebot Node returning error on Connect command

### ISSUE THREAD

**Issue by unclej84** [mrbungle64/node-red-contrib-ecovacs-deebot#1]
When injecting `Deebot command` node with command `Connect` into `Ecovacs Deebot` node the `Ecovacs Deebot` node throws error `TypeError: action.toLowerCase is not a function`

**Comment by mrbungle64** [comment]
@unclej84 

Should be fixed now.

**Comment by unclej84** [comment]
Is working as intended now
