### ISSUE TITLE
T30 Omni - New Device

### ISSUE THREAD

**Issue by KoljaW** [mrbungle64/node-red-contrib-ecovacs-deebot#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Hallo,

hier nochmal ein Issue, damit es richtig zugeordnet wird (ich habe ein Ticket im iobroker Adapter eröffnet).  Hier wurde es ja bereits gefixt. Nochmal DANKE !!! 

In Nodered funktionieren die Befehle nicht (keiner).

### With which model does the problem occur?

Other model (please fill out the fields below)

### Which "other" models are you using?

Deebot Omni T30

### Which version of the ecovacs-deebot node are you using?

 0.4.12

### Which version of Node-RED you have installed?

 v5.2.1

### Which version of Node.js are you using?

v18.19.0

**Comment by mrbungle64** [comment]
@KoljaW 

Ich schaue mal, dass ich in den nächsten Tage ein bisschen Zeit finde eine aktualisierte Version zu veröffentlichen, wo der T30 dann grundsätzlich funktioniert.

**Comment by mrbungle64** [comment]
@KoljaW 

Ich habe gerade die Version 0.4.13 released
Die sollte in der nächste Stunde auch bei den Updates in Node-RED auftauchen

**Comment by KoljaW** [comment]
Funktioniert. Danke
