### ISSUE TITLE
Command "GetCleanLogs" returns empty message (T9)

### ISSUE THREAD

**Issue by unclej84** [mrbungle64/node-red-contrib-ecovacs-deebot#14]
When running `GetCleanLogs` two messages are returned - `CleanLog` with `array[0]` and `LastCleanLogs` with an object of `null` values:

> {"type":"LastCleanLogs","value":{"timestamp":null,"squareMeters":null,"totalTime":null,"totalTimeFormatted":null,"imageUrl":null}}

**Comment by mrbungle64** [comment]
@unclej84 

With OZMO 920, OZMO 930 and Deebot 901 it works properly.

Can you please check the output from the library ([installation and setup](https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Example-apps))

```bash
NODE_ENV=dev node app2.js | grep -E 'Logs|logs'
```
or the full ouput

```bash
NODE_ENV=dev node app2.js
```

**Comment by unclej84** [comment]
Anbei der Mitschrieb ohne den Auth-Teil am Anfang. Kurz vor Schluss steht irgendwas wie "[EcovacsMQTT_JSON] handleCommandResponse() resp(0): GetCleanLogs undefined"
[output.txt](https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot/files/6409856/output.txt)

**Comment by mrbungle64** [comment]
@unclej84 

Ich habe mal den Link zur Datei gelöscht 😉

**Comment by mrbungle64** [comment]
@unclej84 

Hast Du denn in der Mobile App schon ein gefülltes Reinigungsprotokoll?
Dein Gerät ist ja noch sehr frisch und es gab auch immer mal wieder Probleme mit dem Reinigungsprotokoll bei Ecovacs...

**Comment by unclej84** [comment]
Würde sagen ein Protokoll ist da (siehe Screenshot) - habe noch keine geplanten Reinigungen
![Screenshot_20210501-175546_ECOVACS HOME](https://user-images.githubusercontent.com/60842330/116787925-404d4c00-aaa7-11eb-8d8a-5c9788ec6351.jpg)

**Comment by mrbungle64** [comment]
@unclej84 

Hmm, also der Server antwortet ja (mit `ok`) auf die Anfrage:
```js
{"resultCode":"0","resultCodeMessage":"ok","resultData":{"ret":"ok","logs":[]}}
```

Nur stecken da keine Daten drin ...

**Comment by mrbungle64** [comment]
@unclej84 

Hast du die Möglichkeit (ohne viel Aufwand) mal zu sniffen, welchen Befehl die Ecovacs Mobile App beim T9 sendet, zu welcher URL und mit welchen Header Information?

Aktuell benutzt die Library
```bash
[EcovacsMQTT] Calling https://portal-eu.ecouser.net/api/lg/log.do?cv=1.67.3&t=a&av=1.3.1
[EcovacsMQTT] Sending POST to  {"hostname":"portal-eu.ecouser.net","path":"/api/lg/log.do","method":"POST","headers":{"Content-Type":"application/json","Content-Length":243,"User-Agent":"Dalvik/2.1.0 (Linux; U; Android 5.1.1; A5010 Build/LMY48Z)"}}
```

**Comment by skydiver66** [comment]
Hallo, ich kann das leider beim N8 auch bestätigen, es kommen nur noch "null" Werte an und auch die Karten (Adressen) von den Logs sind leer... Es hatte vor kurzem noch funktioniert, vermute dass Ecovacs was geändert hat, Logs in der App laufen normal. Gruß Tom

**Comment by skydiver66** [comment]
Oh, sehe gerade es ist ein alter Post, wie wurde das gelöst?

**Comment by unclej84** [comment]
Ist bisher leider auch beim T9 noch nicht gelöst

**Comment by mrbungle64** [comment]
@skydiver66  @unclej84 

Eigentlich sollte das seit der Version 0.4.5 funktionieren ...
Ist bei euch beiden das Ergebnis mit dieser Version leer?

**Comment by unclej84** [comment]
Oh, Tatsache - jetzt geht es bei mir und "CleanLog" und "LastCleanLogs" kommen gefüllt zurück

**Comment by mrbungle64** [comment]
> Oh, Tatsache - jetzt geht es bei mir und "CleanLog" und "LastCleanLogs" kommen gefüllt zurück

Sehr gut 👍🏻 

Ich muss gestehen, dass ich das Changelog bei den letzten Version schlecht gepflegt habe 🙈

**Comment by skydiver66** [comment]
habe die 0.4.5 aktuell drauf, weiss nicht genau wann ich die geupdatet habe, aber vor ein paar Wochen lief das noch...

**Comment by mrbungle64** [comment]
> habe die 0.4.5 aktuell drauf, weiss nicht genau wann ich die geupdatet habe, aber vor ein paar Wochen lief das noch...

Das heißt, dass das vorher die ganze Zeit schon funktioniert hatte und seit der 0.4.5 nicht mehr?

**Comment by skydiver66** [comment]
das kann ich nicht zu 100 % sagen ob es seit der neuen Version nicht mehr geht, ich hatte vorher einen Ozmo 950, da klappte alles, habe dann den N8 gekauft wegen Mainboardschaden und die NodeRed Klamotte übernommen, da hat es auch noch funktioniert, erst vor kurzem ist mir aufgefallen dass die Karte fehlt und die dazugehörigen Daten der Logs

**Comment by mrbungle64** [comment]
> das kann ich nicht zu 100 % sagen ob es seit der neuen Version nicht mehr geht, ich hatte vorher einen Ozmo 950, da klappte alles, habe dann den N8 gekauft wegen Mainboardschaden und die NodeRed Klamotte übernommen, da hat es auch noch funktioniert, erst vor kurzem ist mir aufgefallen dass die Karte fehlt und die dazugehörigen Daten der Logs

ok, ich denke ich weiß woran es liegt.

Könntest du mal was probieren (um sicher zu gehen), falls du ein bisschen vertraut damit bist wo die Installation von Node-RED im Dateisystem liegt?

**Comment by skydiver66** [comment]
kann es versuchen wenn du mir sagst was :-p

**Comment by mrbungle64** [comment]
> kann es versuchen wenn du mir sagst was :-p

Ja natürlich 😉 

Im Unterverzeichnis `node_modules/node-red-contrib-ecovacs-deebot/node_modules/ecovacs-deebot/library` liegt eine Datei `models.js`.

Dort ändere bitte in folgendem Block

```json
    "n6cwdb": {
        "name": "DEEBOT N8",
        "950type": true,
        "950type_V2": true,
        "main_brush": true,
        "unit_care_info": false,
        "spot_area": true,
        "custom_area": true,
        "mopping_system": true,
        "voice_report": true,
        "auto_empty_station": false,
        "clean_speed": true,
        "map_image_supported": true,
        "type": "T9"
    },
```

der Wert von `type` auf entweder `950` oder `T8`.

Zur Sicherheit dann man Node-RED neu starten und dann schauen ob es (wieder) passt

**Comment by skydiver66** [comment]
sorry, hat bißchen länger gedauert, hab es von T9 in T8 geändert, Neustart gemacht, alles wieder da, super !!!! 1000 Dank... darauf muss man aber auch erstmal kommen :-o

**Comment by mrbungle64** [comment]
> sorry, hat bißchen länger gedauert, hab es von T9 in T8 geändert, Neustart gemacht, alles wieder da, super !!!! 1000 Dank... darauf muss man aber auch erstmal kommen :-o

Alles klar, dann ändere ich das in der Library 👍🏻 
Ich dachte, dass der N8 auch von den Änderungen an der Ecovacs API seit dem T9 betroffen ist.

**Comment by mrbungle64** [comment]
@unclej84 

> Oh, Tatsache - jetzt geht es bei mir und "CleanLog" und "LastCleanLogs" kommen gefüllt zurück

Ich schließe dann mal den Issue 😀
