### ISSUE TITLE
old Deebot support request

### ISSUE THREAD

**Issue by djhui** [mrbungle64/node-red-contrib-ecovacs-deebot#140]
### The feature request

I've used the Deebot DJ35, but seems like doesnt support 

### Which model do you own?

Other model

### Which "other" models are you using?

Deebot DJ35

### Which version of the Ecovacs Deebot node are you using?

10.0.1

### Additional information

Logger: deebot_client.api_client
Source: components/ecovacs/controller.py:81
First occurred: 6:18:36 AM (1 occurrences)
Last logged: 6:18:36 AM

Skipping device as it is not supported: {'did': '[REMOVED]', 'name': 'C3A7C0DAA4602C4C64131835B783F9D6', 'class': 'FORMALECOVACS_LIVING_CLEARROBOT_DJ35_FORMAL', 'resource': None, 'nick': None, 'company': 'ali', 'aliSds': {'sn': 'E0001156018026136130', 'mac': '94:FD:2E:06:E3:25'}}

**Comment by mrbungle64** [comment]
@djhui 

I am not familiar with this model and no longer intend to implement support for older models, sorry ...
