### ISSUE TITLE
Command "GetLifeSpan_side_brush" returns lifespan of side and main brush for T9

### ISSUE THREAD

**Issue by unclej84** [mrbungle64/node-red-contrib-ecovacs-deebot#2]
When injecting command `GetLifeSpan_side_brush` two messages are returned from `Ecovacs Deebot` node - lifespan of side brush (expected) and lifespan of main brush (unintended)

**Comment by mrbungle64** [comment]
@unclej84 

The "problem" is that you have to request each type separately, but in the case of MQTT/JSON type models, the library outputs all values that are already available.
That means if you have already requested the lifespan of main brush, the library will output that value as well.

If you have already requested the lifespan of all 3 types, it will also output an object with all 3 values:

```js
{
    "type": "LifeSpan",
    "value": {
        "filter": 66.86111111111111,
        "sideBrush": 71.73333333333333,
        "mainBrush": 91.28333333333333
    }
}
```

**Comment by mrbungle64** [comment]
@unclej84 

Should also be [fixed](https://github.com/mrbungle64/ecovacs-deebot.js/commit/6d7d60d9cadc59698df7bdbefdf93080f5d3b88d) in the library.

**Comment by mrbungle64** [comment]
@unclej84 

With the latest version of GitHub, the behavior is now a bit more consistent, but for 950 type models (MQTT/JSON) it is recommended to use "GetLifeSpan" (not "GetLifeSpan_side_brush" etc.).

**Comment by unclej84** [comment]
I tested with the latest code and got "GetLifeSpan" correctly.
Strange thing is that if I try e.g. "GetLifeSpan_side_brush" before "GetLifeSpan" it returns a single output. Trying the same directly after "GetLifeSpan" I get all 3 single outputs even when I just requested one. Afterwards a single request does not return anything - "GetLifeSpan" still works then. 

No "GetLifeSpan":
1. "GetLifeSpan_side_brush" - works
2. "GetLifeSpan_main_brush" - works
3. "GetLifeSpan_filter" - works
4. .... (single requests) - works

After "GetLifeSpan":
1. any single request returns all 3 events
2. any following single request returns nothing
3. another "GetLifeSpan" starts at 1. again - no single events available anymore. (had to disconnect and connect again to get to first list)

**Comment by mrbungle64** [comment]
> I tested with the latest code and got "GetLifeSpan" correctly.

Im glad to hear that 👍🏻 

> Strange thing is that if I try e.g. "GetLifeSpan_side_brush" before "GetLifeSpan" it returns a single output. Trying the same directly after "GetLifeSpan" I get all 3 single outputs even when I just requested one. Afterwards a single request does not return anything - "GetLifeSpan" still works then.

That is because the single events only fire if the value has changed.
For the combinded event it'll fire in every case.

Still strange behaviour (due to the problem I described 14 days ago), but more consistent than before, I think ...
So that's why I recommend to use "GetLifeSpan" (without any further argument) to retreive the combined event.

**Comment by unclej84** [comment]
Maybe we should then remove the single commands from command node? Personally I prefer the structured element (can store the output in context data - does not change this often so just request the whole thing periodically with less events)

**Comment by unclej84** [comment]
just like with GetMap returning MapDataObject in the app2.js

**Comment by mrbungle64** [comment]
> Maybe we should then remove the single commands from command node? Personally I prefer the structured element (can store the output in context data - does not change this often so just request the whole thing periodically with less events)

I agree, although the individual commands actually work fine for the non 950 type models 😉

**Comment by mrbungle64** [comment]
> just like with GetMap returning MapDataObject in the app2.js

What do you mean?

**Comment by unclej84** [comment]
In the code for app2.js you recently commented the block with the event listeners for the single events e.g. "Maps", "MapSpotAreas" a. s. o. and just catch "MapDataObject". The ecovacs-deebot node has exactly the same event listeners - so the listener for "LifeSpan_filter" a.s.o. could be removed in favor of "LifeSpan"

**Comment by mrbungle64** [comment]
> In the code for app2.js you recently commented the block with the event listeners for the single events e.g. "Maps", "MapSpotAreas" a. s. o. and just catch "MapDataObject". The ecovacs-deebot node has exactly the same event listeners - so the listener for "LifeSpan_filter" a.s.o. could be removed in favor of "LifeSpan"

ok, but I always have to keep in mind that there are already applications that use the library. Therefore, I would keep the single commands for now. I plan to mark some of them as deprecated.

**Comment by unclej84** [comment]
Are we talking about the ecovacs-deebot.js Library or the ecovacs-deebot node for the node-red-contrib-ecovacs-deebot? I was referring to the last which is probable not used widely until now, or?

**Comment by mrbungle64** [comment]
> Are we talking about the ecovacs-deebot.js Library or the ecovacs-deebot node for the node-red-contrib-ecovacs-deebot? I was referring to the last which is probable not used widely until now, or?

I plan to keep the single commands in ecovacs-deebot.js Library.
For node-red-contrib-ecovacs-deebot I would suggest to use the combined cmds/events (if available).
I also prefer to remove the single LifeSpan commands.

**Comment by unclej84** [comment]
Great - I am on it - currently adding the newly listed combined events and removing the single events for there - will create a PR
