### ISSUE TITLE
Command "GetLifeSpan" does not return anything on T9

### ISSUE THREAD

**Issue by unclej84** [mrbungle64/node-red-contrib-ecovacs-deebot#3]
When injecting command `GetLifeSpan` into `Ecovacs Deebot` node no message is send on output

**Comment by mrbungle64** [comment]
@unclej84 

I just noticed that this is not yet implemented in the library, mainly for the same reason I described in issue #2.

**Comment by mrbungle64** [comment]
@unclej84 

> I just noticed that this is not yet implemented in the library, mainly for the same reason I described in issue #2.

I just fixed the [mentioned](https://github.com/mrbungle64/ecovacs-deebot.js/issues/83) issue in the library.

**Comment by mrbungle64** [comment]
@unclej84 

This issue is fixed in latest version from GitHub.

```js
{
  "type": "LifeSpan",
  "value": {
    "filter": 84.18,
    "side_brush": 86.79,
    "main_brush": 54.36
  }
}
```
