### ISSUE TITLE
Issues connecting to account

### ISSUE THREAD

**Issue by bdydrp** [mrbungle64/node-red-contrib-ecovacs-deebot#35]
Just set this node up
When trying to connect to my deebot account i get this error:
![image](https://user-images.githubusercontent.com/63593828/123097844-dbddb600-d473-11eb-8c6a-68d77041ce8a.png)
Node status just shows red square underneath.

Anything im missing to connect?

**Comment by mrbungle64** [comment]
@bdydrp

Have you already set up ecovacs-account node correctly?

I also need more information. For example:
- Deebot model name
- Node-RED Version
- Node.js version
- Some more information about your flow. Maybe you can post also a screenshot.

**Comment by bdydrp** [comment]
I have set up an ecovacs account and can use/control the vac via ecovacs app
I have a T9+
NR V1.3.5
Unsure where to look for node.js version??
I imported your example flow and changed the 'ecovacs debot' node to my account details.
I have tried setting the account with email/password and with Ecovacs ID. Both give same result

**Comment by mrbungle64** [comment]
> I have set up an ecovacs account and can use/control the vac via ecovacs app
> I have a T9+
> NR V1.3.5
> Unsure where to look for node.js version??

```bash
node -v
```

> I imported your example flow and changed the 'ecovacs debot' node to my account details.

Did you modify something else after importing the exmaple flow?
What are doing when you get that error message and what node is throwing that error message?

> I have tried setting the account with email/password and with Ecovacs ID. Both give same result

What country code are you using?

**Comment by bdydrp** [comment]
> ```shell
> node -v
> ```
V10.24.1 
>
> Did you modify something else after importing the exmaple flow?
> What are doing when you get that error message and what node is throwing that error message?
> 
I added another command node to select a new property. 
Hit deploy and error is thrown
I will remove entire flow and start again without changing anything except account details

> What country code are you using?
Using AU

**Comment by bdydrp** [comment]
So have deleted flow, and re-imported
Only thing I changed was adding my account.
Now debug panel shows this:
![image](https://user-images.githubusercontent.com/63593828/123271461-33e3ed80-d544-11eb-9abf-f95d806dfede.png)

![image](https://user-images.githubusercontent.com/63593828/123271534-49591780-d544-11eb-9881-79551a89331c.png)

**Comment by mrbungle64** [comment]
@bdydrp 

Have you enabled "Connect on startup" or are you triggering "Connect" manually?

> Using AU

Please also try "WW" as country code.

**Comment by bdydrp** [comment]
I have tried connect on start up and manually.
Same outcome

I will try WW as the code!

**Comment by mrbungle64** [comment]
@bdydrp 

> I have tried connect on start up and manually. Same outcome I will try WW as the code!

Have you already tried another country code (e.g. WW)?

**Comment by bdydrp** [comment]
Sorry for the lateness

I tried WW... didnt work
Tried US - Worked!!
Is now connected.. Can control via NR

Thanks for helping out

**Comment by mrbungle64** [comment]
I've added that information to the list of country codes

https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot/wiki/Country-codes
