### ISSUE TITLE
Bild der Karte abrufen 

### ISSUE THREAD

**Issue by skydiver66** [mrbungle64/node-red-contrib-ecovacs-deebot#36]
Hallo Sascha,

gerne stelle ich meine Frage nochmal hier. 
Wie erwähnt ist es mir nicht möglich eine Ausgabe im Debug node zu erhalten wenn ich den inject im ecovacs node starte. 
Alles andere funktioniert bei mir einwandfrei.  
Ich habe Node Red mit der Version 1.3.5 parallel zu Openhabian v3.1.0 und Openhab3 auf meinem RPI 4 (4GB) installiert.  
Der anzusprechende Roboter ist der Ozmo 950 mit der v1.8.2, deinen Adapter habe ich ebenfalls auf 0.3.0 erneuert. 
Vielleicht habe ich etwas übersehen, aber auch mit dem Beispiel flow (get mapimage) funktioniert es nicht.

VG
Tom

**Comment by mrbungle64** [comment]
Hallo @skydiver66 

hast Du die canvas Library installiert?
https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Installation#dependencies

**Comment by skydiver66** [comment]
öhh.... das weiß ich jetzt gar nicht so genau, ich habe bei diesem smarthome projekt schon so viele Sachen installiert...
wie finde ich es heraus? :-P

**Comment by skydiver66** [comment]
OK... das war es.... jetzt habe ich ein Bild.... 1000 Dank :-)

**Comment by mrbungle64** [comment]
@skydiver66 

> OK... das war es.... jetzt habe ich ein Bild.... 1000 Dank :-)

Freut mich, dass es jetzt funktioniert 👍🏻 

Im Endeffekt hatte ja auch die Info dazu noch gefehlt 😉 
Ich habe es nun in der Readme erwähnt, dass man für manche Map-relevanten Funktionen die canvas Library installiert haben muss.
