### ISSUE TITLE
Node-Red crashes when the internet connection is lost

### ISSUE THREAD

**Issue by firestorm96** [mrbungle64/node-red-contrib-ecovacs-deebot#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

Node-Red crashes after about 1min if the internet connection is lost.
This only happens if the Deebot-Node was connected to the server in the first place.

### With which model does the problem occur?

Deebot T8 series

### Which version of the ecovacs-deebot node are you using?

0.3.8

### Which version of Node-RED you have installed?

1.2.9

### Which version of Node.js are you using?

14.16.0

### Anything in the logs that might be useful?

```txt
Jan 29 05:33:46 CCU daemon.err node-red: 29 Jan 05:33:46 - [red] Uncaught Exception:
Jan 29 05:33:46 CCU daemon.err node-red: 29 Jan 05:33:46 - Error: read ECONNRESET
Jan 29 05:33:46 CCU daemon.err node-red:     at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
Jan 29 05:33:47 CCU daemon.err node-red: Node-RED exited with non-zero exit status 1
```

**Comment by mrbungle64** [comment]
@firestorm96 

> Which version of Node.js are you using?
> 14.16.0

As far as I know 14.16.0 is not a valid version number 😉

**Comment by firestorm96** [comment]
Habe grade festgestellt, dass du auch deutsch sprichst 😄

Ich verwende momentan das "RedMatic"-Addon für meine CCU (HomeMatic-Zentrale):
https://github.com/rdmtc/RedMatic/releases

dort wird als Node.js-Version 14.16.0 angegeben (https://nodejs.org/de/blog/release/v14.16.0/).

Oder versteh ich grade was falsch?

**Comment by mrbungle64** [comment]
@firestorm96 

Sorry, ich hatte irgendwie 14.60.0 gelesen 😅 
Die Version 14.16.0 ist allerdings keine aktuelle Version mehr. Das wäre für 14.x aktuell die 14.18.3

Welche Befehle sendest Du denn mit der Ecovacs Deebot Node?
Besonders interessant wäre natürlich was kurz bevor der Fehler auftritt gesendet wurde.

**Comment by firestorm96** [comment]
@mrbungle64 

Befehle sende ich zu dem Zeitpunkt gar keine.

Node.js is bei mir laut den Logs jeden Morgen um ca. 5:30 Uhr abgestürzt (hatte in meinem Router noch die Zwangstrennung drin, daher genau zu der Zeit kein Internet).

Habe vorhin zum testen mal alle Flows entfernt, einen neuen Flow nur mit dem Ecovacs-Deebot-Node erstellt und dann das Internet getrennt -> nach ca. einer Minute stürzt Node-Red dann ab. 

Wenn ich das Node entferne oder einfach deaktiviere, läuft Node-Red auch ohne Internet ohne Probleme.

Ich nehme mal an, dass er ca. jede Minute überprüft, ob die Verbindung zum Ecovacs-Server noch steht und wenn nicht schmiert halt alles ab 😄

**Comment by mrbungle64** [comment]
@firestorm96 

> Ich nehme mal an, dass er ca. jede Minute überprüft, ob die Verbindung zum Ecovacs-Server noch steht und wenn nicht schmiert halt alles ab

Welche Komponente meinst Du?

**Comment by firestorm96** [comment]
@mrbungle64 
Das "Ecovacs Deebot"-Node:
![grafik](https://user-images.githubusercontent.com/31468078/151671187-7f4c44a0-c63e-48ad-b892-7e107b0b3110.png)

**Comment by mrbungle64** [comment]
@firestorm96 

Ich wüsste jetzt nichts davon, dass die Node selbst das tut - aber ich werde mir das noch mal anschauen und versuchen das Verhalten nachzustellen.

**Comment by mrbungle64** [comment]
@firestorm96 

Ich kann das Verhalten nachstellen und damit bestätigen.

Der Fehler selbst tritt zwar offensichtlich im TLSWrap Modul von Node.js auf - wird aber durch einer der ecovacs-deebot Komponenten ausgelöst und dort nicht abgefangen.

Das schaue ich mir dann so bald wie möglich mal genauer an.

**Comment by mrbungle64** [comment]
@firestorm96 

Mit der Version 0.3.11 sollte das Verhalten merklich besser sein.

Das Problem hängt mit dem MQTT Client - welcher in der ecovacs-deebot Library verwendet wird - zusammen:
Der `keepalive` Wert vom MQTT Client hat als Standardwert 60 Sekunden. Daher war auch Deine Annahme "Ich nehme mal an, dass er ca. jede Minute überprüft, ob die Verbindung zum Ecovacs-Server noch steht und wenn nicht schmiert halt alles ab" nicht total verkehrt 😉 Allerdings hatte ich den Wert nicht explizit gesetzt - daher war mir das nicht bewusst.

Nach dieser Minute hat es also geknallt. Offensichtlich beim Reconnect - das ist zumindest jetzt meine Erfahrung und Erkenntnis.
Btw: Da scheinen auch ein paar andere Node-RED Flows von betroffenen zu sein, wo Websockets zum Einsatz kommen.

Jetzt sollte der Fehler von diesem TLSWrapper aber besser abgefangen werden. Ich hoffe Du kannst das soweit bestätigen 😉

**Comment by mrbungle64** [comment]
@firestorm96 

Mit der Version 0.3.12 sollte das Problem endgültig gefixt sein.

Für die MQTT Library kam heute ein Update raus - diese Version wird nun verwendet.
Wie schon vermutet lag da das eigentliche Problem. [Der Bug](https://github.com/mqttjs/MQTT.js/pull/1401) wurde mit [dieser Version](https://github.com/mqttjs/MQTT.js/releases/tag/v4.3.5) gefixt.
