### ISSUE TITLE
TypeError while connected

### ISSUE THREAD

**Issue by Fr3d3rick83** [mrbungle64/node-red-contrib-ecovacs-deebot#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

I´m using Node Red 2.2.2 on Docker and installed node-red-contrib-ecovacs-deebot 0.3.13.
I inserted my Ecovacs login and it says "connected", when I add a debug filter behind the ecovacs node, I get this error:
"TypeError: action.toLowerCase is not a function"

But i receive informations like: object type: "BatteryInfo" value: 75 unit: "%"

### With which model does the problem occur?

Deebot T8 series

### From which source you have installed the adapter?

GitHub

### Version of the ecovacs-deebot.js library

0.3.13.

### Version of Node.js

Node Read is installed via Docker.

### Operating system

Other

**Comment by mrbungle64** [comment]
@Fr3d3rick83 

What commands have you tried so far?

**Comment by mrbungle64** [comment]
@Fr3d3rick83 

It seems that you are sending a command with an empty payload.
Are you using a "Deebot command" node or a self created node?

**Comment by Fr3d3rick83** [comment]
This is, how I set it up:
https://www.dropbox.com/s/j3cj8pimykt8ha5/Bildschirmfoto_2022-04-15_um_17.14.24.png?dl=0

**Comment by mrbungle64** [comment]
> This is, how I set it up: https://www.dropbox.com/s/j3cj8pimykt8ha5/Bildschirmfoto_2022-04-15_um_17.14.24.png?dl=0

It's not going to work that way.

You import an example flow using the Import function of Node-RED:

![Node-RED Import 2022-04-16 17 00 12](https://user-images.githubusercontent.com/37313763/163679937-3f5e8c19-f7fb-4d2c-94b9-ab2667bec588.jpeg)

**Comment by mrbungle64** [comment]
@Fr3d3rick83 

Does it work now?

**Comment by Fr3d3rick83** [comment]
Sorry, I´m on vacation. So how can I trigger the commands?

**Comment by mrbungle64** [comment]
@Fr3d3rick83 

> So how can I trigger the commands?

Have you already had a look at the example flows?

I have also added a section in the readme file:
https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot#examples

**Comment by Fr3d3rick83** [comment]
Yes, its working now, Thanks
