### ISSUE TITLE
Command node - injection with msg.payload

### ISSUE THREAD

**Issue by unclej84** [mrbungle64/node-red-contrib-ecovacs-deebot#6]
According to the code the command node also accepts commands and arg via msg.payload, msg.arg or/and msg.arg2.

When adding the node without command selected the input is used for passing command and args to Deebot node but it shows invalid argument (red triangle) in the node editor of node-red. The input command is executed correctly.

![image](https://user-images.githubusercontent.com/60842330/116781688-da4fcd00-aa84-11eb-8649-15f2b4f97af4.png)

When adding the node with command the input is ignored and the selected command is always used.

Maybe the order of checks in the deebot-command.js should be switched (first check for msg and then fallback to command) or an additional value in commands drop-down for command input via msg.
Injecting a command via msg would make it much more flexible.

**Comment by mrbungle64** [comment]
@unclej84 

You can send commands and arguments via msg.payload driectly to the ecovacs-deebot-node instead of ecovacs-deebot-command.

**Comment by unclej84** [comment]
Ah, great - works fine - definetly some information for #5
