### ISSUE TITLE
deebot ozmo 905 doesn't receive command

### ISSUE THREAD

**Issue by rdl987** [mrbungle64/node-red-contrib-ecovacs-deebot#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

I try to send start spot area cleaning, I see the message from the debug window but the deebot doesn't start.

### With which model does the problem occur?

Deebot OZMO 900/905

### Which version of the ecovacs-deebot node are you using?

0.4.2

### Which version of Node-RED you have installed?

3.0.2

### Which version of Node.js are you using?

14.x

**Comment by mrbungle64** [comment]
@rdl987 

> I try to send start spot area cleaning

Is this the only command that doesn't work?

**Comment by rdl987** [comment]
every command doesn't work. The only think that work is the automatico connection on the ecovacs-deebot node

**Comment by mrbungle64** [comment]
@rdl987 

Do you receive events for battery level etc.?

**Comment by rdl987** [comment]
Yes, I receive the events but only if I set to true the auto connection at startup of the ecovacs-deebot node.
If I send the connect command the connection doesn’t happens

**Comment by mrbungle64** [comment]
@rdl987 

Please use the example flows to check if you are using the nodes correctly:
https://github.com/mrbungle64/node-red-contrib-ecovacs-deebot#examples

**Comment by rdl987** [comment]
> @rdl987
> 
> > The only think that work is the automatico connection on the ecovacs-deebot node
> 
> Do you receive events for battery level etc. after the connection is established?

Yes but it doesn’t work

**Comment by mrbungle64** [comment]
@rdl987 

> > @rdl987
> > > The only think that work is the automatico connection on the ecovacs-deebot node
> > 
> > 
> > Do you receive events for battery level etc. after the connection is established?
> 
> Yes but it doesn’t work

The example flow "Basic Flow" isn't working?

**Comment by mrbungle64** [comment]
@rdl987 

I still need more information 😉 
If the automatic connection but the manual connection not, it seems that there's something wrong with your flow.
That's why I think that it is a good idea to try the example flow ("Basic Flow").

**Comment by rdl987** [comment]
Sorry for the delay.
I solved the problem, I made a mistake with the example. 

Sorry
