### ISSUE TITLE
"TypeError: The "command" argument must be of type string. Received undefined"

### ISSUE THREAD

**Issue by alexoliva91** [mrbungle64/node-red-contrib-ecovacs-deebot#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

I cannot operate on the "Ecovacs Deebot" node because any attempt to initialize the connection would fail with the error `"TypeError: The "command" argument must be of type string. Received undefined"` .
The same happens when using the example flows.

I tried to pass msg.payload both with the Deebot Command node and with a simple input node (of course with a string payload containing just "Connect").

### With which model does the problem occur?

Deebot T9 series

### Which version of the ecovacs-deebot node are you using?

0.4.6

### Which version of Node-RED you have installed?

3.0.2

### Which version of Node.js are you using?

19.6.1

**Comment by unclej84** [comment]
Hi, could you please post the flow / nodes you have used (Ctrl + e)?

**Comment by alexoliva91** [comment]
Hi, sure! I used both the examples provided by the package (those available from the import menu) and this simple node:

`[
    {
        "id": "c2156443169a3e9e",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "363b1f5e275171f7",
        "type": "inject",
        "z": "c2156443169a3e9e",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "Connect",
        "payloadType": "str",
        "x": 220,
        "y": 240,
        "wires": [
            [
                "2a15740e8e131ac5"
            ]
        ]
    },
    {
        "id": "9e759b86a17d18cb",
        "type": "debug",
        "z": "c2156443169a3e9e",
        "name": "debug 9",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 500,
        "y": 240,
        "wires": []
    },
    {
        "id": "2a15740e8e131ac5",
        "type": "ecovacs-deebot",
        "z": "c2156443169a3e9e",
        "account": "076723ab330c229e",
        "name": "myT9",
        "deviceNumber": "1",
        "connectOnStartup": false,
        "enableGetMapsOnStartup": false,
        "enableSimpleEvents": false,
        "login": "ecovacs.com",
        "x": 360,
        "y": 240,
        "wires": [
            [
                "9e759b86a17d18cb"
            ]
        ]
    },
    {
        "id": "076723ab330c229e",
        "type": "ecovacs-account",
        "countryCode": "IT",
        "name": "myHome",
        "login": "ecovacs.com"
    }
]`

**Comment by unclej84** [comment]
Hi @alexoliva91,

sorry for the delay - I have just checked with a fresh installatin of Node.js 19.6.1, Node-RED 3.0.2 and node 0.4.6 and the connect with your flow works right out of the box without issues. I changed countryCode to "DE" - maybe that is the issue. Could you please try again with countryCode "WW" or "US"?

**Comment by unclej84** [comment]
![image](https://user-images.githubusercontent.com/60842330/229310364-f8539fcc-9590-4049-a212-09a5c70a6239.png)

**Comment by mrbungle64** [comment]
@alexoliva91 @unclej84 

I just released version 0.4.8

With Version 0.4.6 one of the Deebot API endpoints was changed.
I don't think that it caused a problem with the "IT" country code, but there was a problem with country codes that use continent "WW". This should be fixed now.
